### ISSUE TITLE
Viz/graph of tasks

### ISSUE THREAD

**Issue by zifeo** [zifeo/whiz#100]
`whiz --graph` should output an ascii visualisation of the tasks and their dependency. Format is free but should support large graphs.

**Comment by Darioazzali** [comment]
Have a working solution here.
Possibility to view the graph with [box-character](https://en.wikipedia.org/wiki/Box-drawing_character) as well.
For now I've just made a binary crate that parse *yaml* file from command line and generate the correspondent graph.
The file has a structure similar from the `resolved` whiz tasks dependency list in main function:
```yml
task_1:
   depends_on:
       - other_task
       - antother_task
task_2:
    depends_on: []
#...
```
In the upper bar there are the tasks that haven't dependency with the others, in the bottom you have the dependent tasks graph.

![task_graph](https://github.com/zifeo/whiz/assets/90763809/76626f54-d9c7-45f6-9009-2974af3c0b28)
I've also made a function for generate casual big dag for checking the representation.
I've used a binary crates that helps draw from nodes and edges lists *termgraph*.
There are others solution that I've found : 
- a perl mdule called Graph-Easy that allows to get ascii representation parsing a `dot` file. 
- `petgraph` and  `graphviz-rust`. The last one needs `graphviz` binary already installed in order to parse the graph into the `.dot` file, but neither of those crates has an ascii representation
Waiting for feedback!
