### ISSUE TITLE
Run task then exit support

### ISSUE THREAD

**Issue by zifeo** [zifeo/whiz#83]
Might be useful in CI to re-use whiz run definitions

**Comment by abdiu34567** [comment]
Hello @zifeo,

I've taken a keen interest in the "Run task then exit support" feature, and I believe I can help implement it. From my understanding, the goal is to provide an option for whiz to execute a task and then exit, which could be particularly useful in CI environments.

Before I start diving into the code, I'd appreciate some clarity on a few points:

Expected Behavior: When the option is enabled, should whiz execute only the specified task and then exit immediately after its completion, without monitoring for any further file changes?
Flag Naming: Do you have any preference for the command-line flag's name that will trigger this behavior? Something like --once or --run-once perhaps?
Output: Is there any specific output format or logging level expected when running in this mode, especially considering CI environments?
Once I have a clearer picture, I'll begin working on a draft PR for initial feedback. Looking forward to collaborating on this!

**Comment by Yohe-Am** [comment]
Oh my. @abdiu34567, I'm sorry, I should have mentioned it here but I've already opened a PR that addresses this issue.
