### ISSUE TITLE
Option to use vertical tabs instead of horizontal tabs

### ISSUE THREAD

**Issue by zifeo** [zifeo/whiz#95]

**Comment by Darioazzali** [comment]
Since ratatui doesn't provide a way to stack the `Tabs` title in a vertical way a solution could be to implement a wrapper on the `List` (stateful List) and `Tabs` that draws (render) differently based on the selected orientation.
Here there is a minimal example with the basic `List`widget:
![try](https://github.com/zifeo/whiz/assets/90763809/28bbfa23-f86b-45f9-a9a7-2bb8681271d2)
This example still does not have the select feature on the list.
A question would be if the key bindings should change too as the `k`, `j` are used to scroll the task content.

**Comment by zifeo** [comment]
@Darioazzali good progress, a few ideas to answer : 
- maybe this should support modes like vim (menu and show) to switch between what is moved
- even if the menu is vertical keeping lateral arrows sound ok
- do forget to manage cases with the text is longer than the allowed width (most of the screen should be for logs and minimise the menu
- a key to switch between the 2 modes

**Comment by Darioazzali** [comment]
Perfect @zifeo , thanks for your reply:

1. Perfect, love vim, everything that resembles it’s fantastic.
2. Ok.
3. If I’ve understood you mean the log content. If this is the case the text wrap as layout changes and/or the menu disappear so will be not a problem.
4. For switching from Menu mode to Show mode I’ve simply put ‘m’ and ‘tab’ for changing layout between horizontal and vertical.
Here you have a simple gif/demo
I've simply replaced the logs with custom mocks.
![try2](https://github.com/zifeo/whiz/assets/90763809/f61eb521-33a9-4bef-9c8d-fd3d24661c11)
Waiting for feedback

**Comment by zifeo** [comment]
@Darioazzali Looks good!
